language: csharp
solution: MatterControl.sln
mono: beta

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/5b68b1f0839bafdd2655
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always